"""Build a comprehensive manager-ready PDF report from a computed plan result."""

import io
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, PageBreak,
)

from .charts import year_trend_png, staffing_curve_png, daily_bar_png, intraday_overlay_png

_HEAD = colors.HexColor("#E8ECFB")
_GRID = colors.HexColor("#C9CFE0")
_ALT = colors.HexColor("#F6F7FB")


def _table(rows, col_widths=None):
    t = Table(rows, hAlign="LEFT", colWidths=col_widths)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), _HEAD),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.4, _GRID),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, _ALT]),
    ]))
    return t


def _img(png: bytes, width=16 * cm):
    if not png:
        return None
    img = Image(io.BytesIO(png))
    ratio = img.imageHeight / img.imageWidth
    img.drawWidth = width
    img.drawHeight = width * ratio
    return img


def build_pdf(result: dict, plan: dict, explanation: str | None = None,
              review: str | None = None) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=1.4 * cm, bottomMargin=1.4 * cm)
    styles = getSampleStyleSheet()
    flow = []
    holiday = plan.get("holiday") or {}

    # ---- Cover / summary ----
    q = plan.get("queue") or {}
    queue_line = ""
    if q.get("name") or q.get("region"):
        queue_line = (f"Queue: <b>{q.get('name') or '—'}</b> &nbsp;|&nbsp; "
                      f"Region: {q.get('region', '—')} &nbsp;|&nbsp; Type: {q.get('type', '—')}<br/>")
    flow.append(Paragraph("WFM Holiday Plan — Report", styles["Title"]))
    flow.append(Paragraph(
        f"{queue_line}"
        f"Holiday: <b>{holiday.get('name', '—')}</b> &nbsp;|&nbsp; "
        f"Plan date: {holiday.get('plan_date', '—')} &nbsp;|&nbsp; "
        f"Total shrinkage: {result['shrinkage']['total_shrinkage_pct']}%", styles["Normal"]))
    flow.append(Spacer(1, 0.4 * cm))

    rows = [["Channel", "Combo", "Weekly fcst", "Busiest", "Peak Net", "Peak Gross"]]
    for ch, res in result["channels"].items():
        rows.append([ch, (res["recommended"] or {}).get("combo", "—"),
                     f"{res['weekly_forecast']:,.0f}", res["busiest_day"],
                     str(res["peak_net_hc"]), str(res["peak_gross_hc"])])
    flow.append(_table(rows))
    flow.append(Spacer(1, 0.5 * cm))
    flow.append(Paragraph(
        "<i>All figures are produced by deterministic WFM formulas (Erlang C, compound "
        "shrinkage, throughput). Numbers are reproducible and auditable.</i>", styles["Italic"]))

    # ---- AI analysis (explanation + review) ----
    if explanation or review:
        flow.append(PageBreak())
        flow.append(Paragraph("AI Analysis", styles["Heading1"]))
        flow.append(Paragraph(
            "<i>Generated by an LLM from the computed figures. The AI explains and advises "
            "only — it never produces or changes any number.</i>", styles["Italic"]))
        flow.append(Spacer(1, 0.3 * cm))
        if explanation:
            flow.append(Paragraph("Plan summary", styles["Heading3"]))
            flow.append(Paragraph(explanation.replace("\n", "<br/>"), styles["Normal"]))
            flow.append(Spacer(1, 0.4 * cm))
        if review:
            flow.append(Paragraph("Analyst review &amp; suggestions", styles["Heading3"]))
            for line in review.split("\n"):
                line = line.strip().lstrip("*-• ").strip()
                if line:
                    flow.append(Paragraph("• " + line, styles["Normal"]))
                    flow.append(Spacer(1, 0.08 * cm))

    # ---- Per-channel detail (charts + tables) ----
    for ch, res in result["channels"].items():
        flow.append(PageBreak())
        reco = res["recommended"] or {}
        flow.append(Paragraph(f"{ch.capitalize()}", styles["Heading1"]))
        flow.append(Paragraph(
            f"Recommended trend <b>{reco.get('combo', '—')}</b> "
            f"({reco.get('blended_impact_pct', 0):+.1f}% vs plan) → forecast "
            f"{res['weekly_forecast']:,.0f}/week. Peak staffing on {res['busiest_day']}: "
            f"{res['peak_net_hc']} net → <b>{res['peak_gross_hc']} gross</b> agents.",
            styles["Normal"]))
        flow.append(Spacer(1, 0.3 * cm))

        # Diagram 1 — year trend + forecast
        im = _img(year_trend_png(res, ch))
        if im: flow.append(im)
        # Daily bar
        im = _img(daily_bar_png(res, ch))
        if im: flow.append(im)
        # Diagram 2 — staffing curve (skips for email)
        im = _img(staffing_curve_png(res, ch))
        if im:
            flow.append(im)
        # Diagram 6 — intraday overlay (only when per-year intraday history was supplied)
        im = _img(intraday_overlay_png(res, ch))
        if im:
            flow.append(im)

        # Multi-day staffing (each day with volume planned independently)
        days_hc = res.get("days_hc") or []
        if len(days_hc) > 1:
            flow.append(Spacer(1, 0.3 * cm))
            flow.append(Paragraph("Multi-day staffing (each day planned independently)", styles["Heading3"]))
            mrows = [["Day", "Volume", "Net HC", "Gross HC"]]
            for d in days_hc:
                mrows.append([d["day"] + (" (peak)" if d["day"] == res.get("busiest_day") else ""),
                              f"{d['volume']:,.0f}", str(d["peak_net_hc"]), str(d["peak_gross_hc"])])
            flow.append(_table(mrows))

        # Combinations table
        flow.append(Spacer(1, 0.3 * cm))
        flow.append(Paragraph("Trend combinations (scored)", styles["Heading3"]))
        crows = [["Combination", "Impact %", "Forecast", "Score", "Reco"]]
        for c in res["combinations"]:
            crows.append([c["combo"], f"{c['blended_impact_pct']:.2f}",
                          f"{c['forecasted_volume']:,.0f}", f"{c['score']:.1f}",
                          "★" if c["recommended"] else ""])
        flow.append(_table(crows))

        # Interval HC table (voice/chat)
        if res["intervals"]:
            flow.append(Spacer(1, 0.3 * cm))
            flow.append(Paragraph(f"Interval HC — {res['busiest_day']}", styles["Heading3"]))
            irows = [["Slot", "Calls/hr", "Net HC", "Gross HC"]]
            for iv in res["intervals"]:
                irows.append([f"{iv['start']}–{iv['end']}", f"{iv['calls_per_hour']:.1f}",
                              str(iv["net_hc"]), str(iv["gross_hc"])])
            flow.append(_table(irows))

    doc.build(flow)
    return buf.getvalue()
